### ISSUE TITLE
Should we index static placeholders?

### ISSUE THREAD

**Issue by beniwohli** [aldryn/aldryn-search#11]
If yes, how do we figure out which pages contain which static placeholders?

**Comment by jakob-o** [comment]
Hey @czpython,
I know this is an old issue, but I stumbled across this when having static placeholders on app pages. Is there any solution to this at the moment? If I have to fork, would you mind hinting me in the right direction?

Thank you in advance

Jakob

As a side note: I tried to use normal placeholders and manually adding the template to the app page, which seemed to work at first but didn't in the end (I forgot what exactly the problem was). So I went back to static placeholders which are not indexed now...

**Comment by jakob-o** [comment]
Nevermind. I revisited normal placeholders on AppHook pages and they work fine. My problem originated from programatically assigning the template to the page without having it added to CMS_PAGES which led to not being able to save any changes to the page anymore...

**Comment by czpython** [comment]
@jakob-o 
Regarding your first comment, the problem with static placeholders is that they're not attached to anything, so it's not possible to index their content under a specific page.

The only way to do so would be to scan the page's template and check a static placeholder is present (this is likely to come in the future).

Regarding your second comment, I don't recommend placeholders on app hooked pages as they can create some issues down the line.

**Comment by jakob-o** [comment]
Hey @czpython,

would you mind elaborating on the latter? What problems might I face? Is this documented anywhere?

Regards

Jakob
