### ISSUE TITLE
How to make Full text search working?

### ISSUE THREAD

**Issue by garmoncheg** [aldryn/aldryn-search#26]
Is it possible? For now I only have 

    All documents removed.
    Indexing 92 titles

And so the index only contains cms.title objects.
How is it possible to index the djangocms_text_ckeditor plugin instances. I suspect it it supported in this app?

**Comment by stefanfoulis** [comment]
The index will actually contain all plugins on those pages. The "Indexing 92 titles" is an unfortunate way haystack reports succes. It's just called "titles" because the main Model in django-cms, representing a ``Page`` in a certain language is called ``Title``.

See https://github.com/aldryn/aldryn-search/blob/master/aldryn_search/search_indexes.py#L51-53 for where the individual plugins on each ``Page`` are added to the index.
