### ISSUE TITLE
aldryn-search & whoosh backend - how to update_index on Aldryn?

### ISSUE THREAD

**Issue by macolo** [aldryn/aldryn-search#69]
I don't think there is a way to execute `manage.py` commands on the Aldryn life server... So `manage.py update_index` is out of question. (?)

**Comment by macolo** [comment]
Seems this is handled here on the fly: https://github.com/aldryn/aldryn-search/blob/master/aldryn_search/receivers.py

**Comment by macolo** [comment]
I tested this and adding new content to a page and then publish that page does not update the `whoosh` index for me.

**Comment by stefanfoulis** [comment]
The whoosh backend will not work on the Aldryn Platform, because whoosh saves the index on disk. All apps on aldryn run in docker containers that don't have a shared filesystem, so the index would disappear if a container is restarted.
For search we have a closed beta with elasticsearch as a search backend. 
Currently you'll need celery (also a closed beta feature on aldryn) to run the index update periodically in the background.
If you're interested in participating in the closed betas, we can talk on our support chat.
